### ISSUE TITLE
Multiple Copy doesn't work

### ISSUE THREAD

**Issue by mattdmartin** [GCalToolkit/GCalPlus#3]
I just installed GCalPlus primarily for the Multiple Copy feature. I have given it the necessary permissions and the Multiple Copy option is available in Calendar. However, whenever I go through the process, the events do not get copied. Everything appears to work--I get no error messages--but the new events are not created.

**Comment by GCalToolkit** [comment]
Thanks for letting me know, I'll take a look ASAP.

**Comment by GCalToolkit** [comment]
Sorry for the delay - this should be fixed now, can you please make sure you have the latest version running and try again?

**Comment by mattdmartin** [comment]
It is fixed, thanks very much!
